### ISSUE TITLE
JS for the asset website

### ISSUE THREAD

**Issue by originalfoo** [thale5/LSM#4]
Not sure where the source is for this site: https://thale5.github.io/Prefabs/

![assets](https://user-images.githubusercontent.com/1386719/57773009-e8c54280-770e-11e9-84b5-459db29e43e9.jpg)

I saved the Buildings page local and quickly hacked together some js to make it interactive. With some tweaks (namely, `DefaultExceptions` array and `header` string) it should work for vehicles and props too.

* User can click the assets to toggle them.
* Headings can also be clicked (doesn't work very well)
* Items in `DefaultExceptions` array are "locked" to prevent accidental skipping
    * Ctrl+Click to skip them
* Config text is output in page footer, user can just paste it in to their file

CSS updated to:

```css
    <style>
        * {font-family:sans-serif;}
        body {background-color:#f8f4e2;}
        .my {display:-webkit-flex;display:flex;}
        .my div {min-width:30%;margin:1px 1px 1px 10px;font-size:100%;}
        h1 {margin-top:55px;border-bottom:2px solid black;}
        h2 {margin-top:40px;color:#000090;}
        code {display:block;font-family:Consolas, Menlo, Courier, monospace;line-height:125%;padding:10px 10px;background-color:#C2D468;border-radius:7px;}
        .locked code {background-color: #FAB155;}
        .skipped code {background-color: #D8334A;}
        .skipped.locked code {background-color: #EC87C0;}
        pre {white-space:pre;margin:6px 0px;cursor:pointer;}
        footer code { background-color: #F5F7FA;}
        img {display:block;margin:6px 0px;border-radius:7px;box-shadow:8px 6px 10px #5a5a5a;}
        .skipped img {opacity:0.4;}
        a {margin:10px 1px 1px 20px;}
        a:link {color:#000090;font-family:Consolas, Menlo, Courier, monospace;text-decoration:inherit;}
        a:visited {color:#000090;font-family:Consolas, Menlo, Courier, monospace;text-decoration:inherit;}
        a:hover {font-weight:bold;}
    </style>
```

JQuery:

```js

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <script>
        // * Click individual asset to toggle that specific asset
        // * Ctrl+Click individual locked asset to skip it
        // * Click heading (h2) to toggle associated assets (except locked 'DefaultExceptions' assets)
        // * Note: The heading functionality is crappy and doesn't work very well, but don't have time to fix it right now.

        const DefaultExceptions = [
            // # Network connections
            'Road Connection',
            'Road Connection Small',
            'Train Connection',
            'Airplane Connection',
            'Ship Connection',

            // # Pillars
            'MediumBridgePillar',
            'HighwayBridgePillar',
            'HighwayRampPillar',
            'HighwayBridgeSuspensionPillar',
            'LargeRoadBridgeSuspensionPillar',
            'RoadSmallBridgePillar',
            'GravelBridgePillar',
            'RailwayBridgePillar',
            'RailwayElevatedPillar',
            'RailOnewayBridgePillar',
            'RailOnewayElevatedPillar',
            'Pedestrian Elevated Pillar',
            'LargeRoadBikeBridgeSuspensionPillar',
            'Two Lane Highway Bridge Pillar',
            'Two Lane Highway Suspension Pillar',
            'Four Lane Highway Bridge Pillar',
            'Four Lane Highway Suspension Pillar',
            'Wooden Footbridge Pillar 6',
            'Wooden Footbridge Pillar 12',
            'Wooden Footbridge Pillar 18',
            'Wooden Footbridge Pillar 24',
            'Cable Car Pylon 12',
            'Cable Car Pylon 24',
            'Cable Car Pylon 36',
            'Cable Car Pylon 48',
            'Cable Car Pylon 60',
            'Monorail Pylon',
            'Monorail Pylon 2',
            'Monorail Pylon 3',

            // # Road infrastructure
            'Empty Intersection',
            'RoundaboutL',
            'RoundaboutS',

            // # Other infrastructure
            'Integrated Metro Station',
            'Metro Entrance',
            'Water Intake',
            'Water Outlet',
            'Fresh Water Outlet',
            'Eco Water Outlet',
        ];

        let lock = [];
        let skip = [];

        let header, // text of page title (h1)
            footer; // footer code element

        const GetAssetName = ( myAsset ) => {
            const codeElement = myAsset.find( 'code' );

            try {

                return codeElement.html().split( '\n' )[ 0 ];

            } catch (e) {

                console.error(e);
                console.log( myAsset.html() );
            }
        }

        const UpdateConfig = ( myAsset, isLock, isSkip ) => {

            const name = GetAssetName( myAsset );

            const idxSkip = skip.indexOf( name );
            const idxLock = isLock ? lock.indexOf( `Except:${name}` ) : -1;

            if ( isSkip ) {

                skip.push( name );
                if ( isLock ) lock.splice( idxLock, 1 );

            } else {

                skip.splice( idxSkip, 1 );
                if ( isLock ) lock.push( `Except:${name}` );
            }
        }

        const OutputConfig = () => {
            skip.sort();
            lock.sort();

            footer.empty()
                .append( `${header} \n\n` )
                .append( `Buildings: \n\n` )
                .append( `${skip.join('\n')} \n\n`)
                .append( `${lock.join('\n')} \n\n`);
        }

        $( () => {

            const body = $( 'body' );
            const Headings = $( 'h2' ); // list of all headings
            const AssetList = $( 'code' ).closest( '.my' ); // list of all assets on the page

            header = '# ' + $( 'h1', body ).text().toUpperCase();

            body.append( '<footer><h2>Your settings:</h2><pre><code></code></pre></footer>' );
            footer = $( 'footer code', body );

            // init default exceptions
            AssetList.each( function() {

                const myAsset = $( this );

                const name = GetAssetName( myAsset );

                if ( DefaultExceptions.includes( name ) ) {

                    myAsset.addClass( 'locked' );
                    lock.push( `Except:${name}` );
                }
            } );

            let bulk = false;

            // heading toggle
            Headings.click( function( event ) {

                const myHeading = $( this );
                const group = myHeading.text().split( ' ' ).join( '' );

                bulk = true;

                AssetList.filter( `:contains(${group})` ).click();

                bulk = false;

                OutputConfig();
            } );

            // individual asset toggle
            AssetList.click( function( event ) {

                const myAsset = $( this );
                const isLock = myAsset.hasClass( 'locked' );
                const isSkip = myAsset.hasClass( 'skipped' );

                if ( isSkip ) {

                    myAsset.removeClass( 'skipped' );

                } else {

                    // if locked, Ctrl must be pressed to skip
                    if ( isLock && ! event.ctrlKey ) return;

                    myAsset.addClass( 'skipped' );
                }

                UpdateConfig( myAsset, isLock, !isSkip );

                if ( ! bulk ) OutputConfig();
            } );

        } );

    </script>
```

As mentioned above, the clickable headings feature is grim but it was just an afterthought. With a bit more time I could make it work much better. However, some changes to the HTML structure would make life a lot easier so if you can point me at the code that generates it I'll see what I can do (or I could just provide example markup and you do it, whatever).

Sample of config output in footer:

```
Buildings:

1x1_Hotel01
1x1_Restaurant01
1x1_Restaurant02
1x1_Souvenir Shop
1x1_cafe
...
eco_residential_high02_4x3level2 

Except:Airplane Connection
Except:Cable Car Pylon 12
Except:Cable Car Pylon 24
Except:Cable Car Pylon 36
...
Except:Wooden Footbridge Pillar 24
Except:Wooden Footbridge Pillar 6 
```
